package com.example.nts_pim.utilities.enums

enum class LogEnums(val tag: String) {
    TRIP("TRIP"),
    PIM_SETTING("PIM_SETTING"),
    OVERHEATING("OVER_HEATING"),
    BLUETOOTH("BLUETOOTH"),
    AWS_SUBSCRIPTION("AWS_SUBSCRIPTION"),
    INTERNET_CONNECTION("INTERNET_CONNECTION"),
    BUTTON_PRESS("BUTTON_PRESS"),
    LIFE_CYCLE("LIFE_CYCLE"),
    SQUARE("SQUARE"),
    AD_INFO("AD_INFO"),
    TRIP_STATUS("TRIP_STATUS"),
    RECEIPT("RECEIPT"),
    PAYMENT("PAYMENT"),
    TEXT_READER("TEXT_READER"),
    SETUP("SETUP"),
    UPFRONT_PRICE("UPFRONT_PRICE"),
    ERROR("ERROR")
}